FROM apache/airflow:2.9.0-python3.9

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jdk-headless procps && \
    rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

USER airflow
COPY requirements.txt .
RUN pip install --no-cache-dir --force-reinstall numpy==1.24.4
RUN pip install --no-cache-dir -r requirements.txt